config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout', unlock: 'unlock' }

  root 'static#home'

  # get 'my/bio'  => 'static#about'
  # get 'my/work' => 'static#portfolio'

  resources :tidbits, except: [:show, :destroy]
  resources :tidbits, only: [] do # :(
    collection do
      get '/unpublished/:category', to: 'tidbits#index', as: :unpublished_categorized, defaults: { unpublished: true }
      get '/unpublished',           to: 'tidbits#index', as: :unpublished,             defaults: { unpublished: true }
      get '/:category',             to: 'tidbits#index', as: :categorized
    end
  end

end

app/models/tidbit.rb
# == Schema Information
#
# Table name: tidbits
#
#  id             :integer          not null, primary key
#  title          :string           not null
#  content        :text             not null
#  more_info      :text
#  more_info_link :string
#  author_id      :integer
#  created_at     :datetime
#  updated_at     :datetime
#  category       :integer          default(0), not null
#  published      :boolean          default(FALSE)
#

class Tidbit < ActiveRecord::Base
  enum category: ['programming', 'zoology', 'miscellaneous']

  belongs_to :author, class_name: 'Admin'

  validates :author_id, :category, :content, :title, presence: true
  validate  :content_length_cannot_be_greater_than_100_words,
            :title_length_cannot_be_greater_than_10_words

  delegate :name, :shy_name, to: :author, prefix: true

  before_validation :strip_whitespace

  #========================= Class Methods

  # Orders tidbits from most to least recently created
  def self.in_order
    order('created_at DESC')
  end

  # Returns the total count for each category (and all total)
  def self.get_totals
    totals = {}
    self.categories.each{ |name, value| totals[name] = Tidbit.with_category_id(value).size }
    totals['all'] = totals.values.inject(:+)
    return totals
  end

  # Gets tidbits with given category
  def self.with_category(category)
    with_category_id(self.categories[category])
  end

  # Gets tidbits with given category id
  def self.with_category_id(category_id)
    where(category: category_id)
  end

  # Gets published tidbits
  def self.published
    where(published: true)
  end

  # Gets unpublished tidbits
  def self.unpublished
    where(published: false)
  end

  #========================= Instance Methods

  # Gets the integer value for the tidbit's category, based on name
  def category_id
    self.class.categories[self.category]
  end

  # Returns whether the tidbit has text for more info
  def more_info?
    more_info.present?
  end

  # Returns whether the tidbit has a link for more info
  def linked?
    more_info_link.present?
  end

  private

  def content_length_cannot_be_greater_than_100_words # avoiding the "100 words or [less vs fewer]" issue
    if content.split(' ').size > 100
      errors.add(:content, 'cannot be longer than 100 words')
    end
  end

  def title_length_cannot_be_greater_than_10_words
    if title.split(' ').size > 10
      errors.add(:title, 'cannot be longer than 10 words')
    end
  end

  def strip_whitespace
    self.title          = self.title.strip
    self.content        = self.content.strip
    self.more_info_link = self.more_info_link.strip
    self.more_info      = self.more_info.strip
  end

end

app/controllers/tidbits_controller.rb
class TidbitsController < ApplicationController
  before_filter :restrict_to_admin, except: [:index]
  before_filter :load_tidbit, only: [:edit, :update]

  def index
    @unpublished = params[:unpublished] && current_admin

    all_tidbits = @unpublished ? Tidbit.unpublished : Tidbit.published
    @tidbit_totals = all_tidbits.get_totals

    if params[:category] && Tidbit.categories.keys.include?(params[:category])
      @category = params[:category]
      @tidbits  = all_tidbits.with_category(@category).in_order
    else
      @category = 'all'
      @tidbits  = all_tidbits.in_order
    end
  end

  def new
    @tidbit = Tidbit.new
  end

  def create
    @tidbit = current_admin.tidbits.build(tidbit_params)
    if @tidbit.save!
      flash[:success] = 'Tidbit successfully created.'
      redirect_to tidbit_redirect and return
    else
      flash.now[:error] = 'There was an issue creating the tidbit.'
      render :new and return
    end
  end

  def edit
  end

  def update
    if @tidbit.update_attributes!(tidbit_params)
      flash[:success] = 'Tidbit successfully updated.'
      redirect_to tidbit_redirect and return
    else
      flash.now[:error] = 'There was an issue updating the tidbit.'
      render :edit and return
    end
  end

  private

  def load_tidbit
    @tidbit = Tidbit.find(params[:id])
  end

  def tidbit_params
    params.require(:tidbit).permit(:category, :content, :more_info, :more_info_link, :published, :title)
  end

  def tidbit_redirect
    @tidbit.published? ? tidbits_path : unpublished_tidbits_path
  end

end

app/helpers/tidbits_helper.rb
module TidbitsHelper

  # Puts together tidbits category options for form select
  def tidbit_category_options(selected = nil)
    options_for_select(tidbit_categories.map{ |category| [ category.titleize, category ] }, selected: selected)
  end


  # Gets category names, alphabetized
  def tidbit_categories
    Tidbit.categories.keys.sort
  end

  # Adds 'all' to list of tidbit categories
  def all_tidbit_categories
    tidbit_categories.unshift('all')
  end

  # Returns the path for the given category of tidbits
  def tidbits_path_for(category, published = true)
    if category == 'all'
      published ? tidbits_path : unpublished_tidbits_path
    else
      published ? categorized_tidbits_path(category) : unpublished_categorized_tidbits_path(category)
    end
  end
end

app/views/tidbits/_category_menu.html.erb
<p>Choose a Category:</p>
<div class='list-group'>
  <% all_tidbit_categories.each do |category| %>
    <%= link_to tidbits_path_for(category, published), class: "list-group-item#{' active' if currently == category}" do %>
      <%= category.titleize %><span class='badge badge-primary'><%= tidbit_totals[category] %></span>
    <% end %>
  <% end %>

  <% if current_admin %>
    <p class='text-right'><%= link_to "View #{published ? 'Unpublished' : 'Published'} Tidbits", tidbits_path_for(currently, !published) %></p>
  <% end %>
</div>

app/views/tidbits/_form.html.erb
<%= form_for tidbit, html: { class: 'form-horizontal' } do |f| %>

  <div class='form-group'>
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :category, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.select :category, tidbit_category_options(tidbit.category), class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :content, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :more_info_link, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :more_info_link, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :more_info, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_area :more_info, class: 'form-control', rows: 5 %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
      <div class='checkbox'>
        <%= f.label :published do %>
          <%= f.check_box :published %>
          Publish
        <% end %>
      </div>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
      <%= f.submit class: 'btn btn-k7r' %>
    </div>
  </div>

<% end %>

app/views/tidbits/_tidbit.html.erb
<div class='row tidbit'>
  <div class='col-xs-10 col-xs-offset-1'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h2 class='panel-title'>
          <%= tidbit.title %>
          <%= content_tag(:small, tidbit.author_shy_name) unless tidbit.author_name == 'Katie Russ' %><!-- I am temporarily hiding author names, since all are authored by me -->
          <%= link_to 'Edit Tidbit', edit_tidbit_path(tidbit), class: 'pull-right' if current_admin %>
        </h2>
      </div>

      <div class='panel-body'>
        <p><%= markdown tidbit.content %></p>
      </div>

      <% if tidbit.more_info? || tidbit.linked? %>
        <div class='panel-footer'>
          <span>More info:</span>
          <%= link_to tidbit.more_info_link, tidbit.more_info_link, target: '_blank' if tidbit.linked? %>
          <% if tidbit.more_info? %>
            <p><%= markdown tidbit.more_info %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tidbits/_tidbits_menu.html.erb
<p>Choose a Category:</p>
<div class='list-group'>
  <% all_tidbit_categories.each do |category| %>
    <%= link_to tidbits_path_for(category), class: "list-group-item list-group-item-k7r#{' active' if currently == category}" do %>
      <%= category.titleize %><span class='badge badge-primary'><%= tidbit_totals[category] %></span>
    <% end %>
  <% end %>
</div>

app/views/tidbits/edit.html.erb
<h1>Edit an Existing Tidbit</h1>
<%= render 'form', tidbit: @tidbit %>

app/views/tidbits/index.html.erb
<header>
  <div class='row' id='tidbits'>
    <div class='col-sm-6 col-xs-10 col-xs-offset-1'>
      <h1>Tidbits<%= content_tag(:small, ' (Unpublished)') if @unpublished %></h1>

      <h2><small>This is a collection of interesting things I have come across, including programming tricks, animal facts, and whatever other miscellaneous tidbits I feel are worth sharing, each in under a hundred words. Enjoy!</small></h2>
    </div>

    <div class='col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-0 col-xs-10 col-xs-offset-1'>
      <%= render 'category_menu', currently: @category, tidbit_totals: @tidbit_totals, published: !@unpublished %>
    </div>
  </div>
</header>

<%= render partial: 'tidbit', collection: @tidbits %>

app/views/tidbits/new.html.erb
<header>
  <div class='row' id='tidbits'>
    <div class='col-xs-10 col-xs-offset-1'>
      <h1>Create a New Tidbit</h1>
    </div>
  </div>
</header>

<%= render 'form', tidbit: @tidbit %>