config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout', unlock: 'unlock' }

  root 'static#home'

  # get 'my/bio'  => 'static#about'
  # get 'my/work' => 'static#portfolio'

  resources :tidbits, except: [:show, :destroy]
  resources :tidbits, only: [] do # :(
    collection do
      get '/unpublished/:category', to: 'tidbits#index', as: :unpublished_categorized, defaults: { unpublished: true }
      get '/unpublished',           to: 'tidbits#index', as: :unpublished,             defaults: { unpublished: true }
      get '/:category',             to: 'tidbits#index', as: :categorized
    end
  end

end

app/views/layouts/_admin_nav.html.erb
<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Admin <span class='caret'></span></a>
<ul class='dropdown-menu'>
  <li><%= link_to 'Add New Tidbit', new_tidbit_path %></li>
  <li role='separator' class='divider'></li>
  <li><%= link_to "Logout #{current_admin.name}", destroy_admin_session_path, method: :delete %></li>
</ul>

app/views/layouts/_application_nav.html.erb
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand#{' active' if home?}" do %>kathleen.codes<%= sr('(current)') if home? %><% end %>
    </div>

    <div id="navbar" class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if tidbits? %>">
          <%= link_to tidbits_path do %>Tidbits<%= sr('(current)') if tidbits? %><% end %>
        </li>
        <li class="<%= 'active' if portfolio? %>">
          <%= link_to my_work_path do %>Portfolio<%= sr('(current)') if portfolio? %><% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class='footer navbar-inverse navbar-static-bottom'>
  <div class='container'>
    <div class='row'>

      <div class='col-md-8 col-sm-9 col-xs-7'>
        <span class='navbar-text'>
          Contact:
          <%= my_email %>
        </span>

        <span class='navbar-text'>
          <ul class='list-unstyled list-inline social nobr'>
            Connect:
            <li>
              <a href='https://github.com/katie7r' target='_blank' class='btn btn-k7r btn-xs btn-icon'>
                <%= icon('soc-gh', 'GitHub') %>
              </a>
            </li>

            <li>
              <a href='https://twitter.com/katie_k7r' target='_blank' class='btn btn-k7r btn-xs btn-icon'>
                <%= icon('soc-tw', 'Twitter') %>
              </a>
            </li>

            <li>
              <a href='https://www.linkedin.com/pub/kathleen-russ/b1/377/49a' target='_blank' class='btn btn-k7r btn-xs btn-icon'>
                <%= icon('soc-li', 'LinkedIn') %>
              </a>
            </li>
          </ul>
        </span>
      </div>

      <div class='col-md-2 col-sm-3 col-xs-5'>
        <span class='navbar-text navbar-right'>
          &copy; 2015 Katie Russ
        </span>
      </div>

      <div class='col-md-2 col-sm-3 col-xs-5'>
        <span class='navbar-text text-muted navbar-right'>
          <a href='#top'><%= icon('up-small', 'Up Arrow') %>Back to Top</a>
        </span>
      </div>
    </div>

    <%= link_to icon('lock-filled', 'Open Lock'), new_admin_session_path, class: 'secret-tunnel' unless current_admin %>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<a href='#main-content' class='sr-only sr-only-focusable'>Skip to main content</a>

<nav class='navbar navbar-inverse navbar-static-top' id='top'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <span class='k7r'>
        <%= link_to root_path, class: "navbar-brand#{' active' if home?}" do %>
        katie<span class='k7r-mark'>r</span>.codes<%= sr('(current)') if home? %>
        <% end %>
      </span>
    </div>

    <div id='navbar' class='collapse navbar-collapse navbar-right'>
      <ul class='nav navbar-nav'>
        <li class='<%= 'active' if tidbits? %>'>
          <%= link_to tidbits_path do %>Tidbits<%= sr('(current)') if tidbits? %><% end %>
        </li>
        <% if current_admin %>
          <li class='dropdown'><%= render 'layouts/admin_nav' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_splash_jumbo.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>OH HAI.</h1>

    <p class="lead">Sorry, I didn't see you there. Come in, come in!</p>

    <p>
      Welcome to my humble site. Come, sit! Warm yourself by the fire, and please help yourself to some
      Lorem Ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus
      a velit blandit tempor. Morbi faucibus enim non turpis consequat eleifend. Quisque nec neque sed
      purus feugiat ultrices eget id turpis. Aliquam vestibulum ut dolor vel laoreet. Aliquam faucibus,
      nibh ac lacinia tincidunt, massa lectus tincidunt ipsum, at egestas ante dui et justo. Nulla in
      eleifend urna. Nunc vehicula suscipit nisl, sed feugiat magna faucibus sit amet. Nam non convallis
      velit. Nam risus est, bibendum nec erat eleifend, ornare ultricies nunc. Aliquam lobortis odio id
      nisi vulputate, sed dapibus leo pellentesque. Nulla facilisi.
    </p>
  </div>

  <div class="col-md-4">
    <%= image_tag 'owl.png', alt: 'Megascops albogularis, or the White-throated screech owl', class: 'img-responsive center-block' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Katie Russ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel='shortcut icon' type='image/png' href='<%= asset_path 'favicon.png' %>'/>
  <link rel='shortcut icon' type='image/png' href='<%= asset_url 'favicon.png' %>'/>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body role='document'>

  <%= render 'layouts/nav' %>

  <%= render 'static/intro' if home? %>

  <%= render 'shared/flash_messages', flash: flash unless flash.empty? %>
  <div class='container<%= ' home' if home? %>' role='main'>
    <div id='main-content'>
      <%= yield %>
    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kathleen.codes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body role="document">

  <div class="jumbotron" id="landing-jumbo">
    <div class="container">
      <%= render 'layouts/landing_jumbo' %>
    </div>
  </div>


  <div class="container landing" id="content" role="main">
    <%= render 'shared/flash_messages', flash: flash %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kathleen.codes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body role="document">

  <div class="jumbotron" id="splash-jumbo">
    <div class="container">
      <%= render 'layouts/splash_jumbo' %>
    </div>
  </div>


  <div class="container splash" id="content" role="main">
    <%= render 'shared/flash_messages', flash: flash %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>